language: node_js

node_js:
  - "17.2.0"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir:  ./dist/
  on:

