language: node_js
node_js:
  - "16"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

notifications:
  slack: '<sytw>:<GgiUiOJJeifKY0uamYUGF1Zr>#01'     

install:
  - npm install

script:
  - cd server
  - npm start
  - cd ..
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless