language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm install
  - npm run build
  - npm run test
