language: node_js
node_js:
  - "16"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

script:
  - travis encrypt "sytw:GgiUiOJJeifKY0uamYUGF1Zr#01" --add notifications.slack.rooms

notifications:
  slack: '<sytw>:<GgiUiOJJeifKY0uamYUGF1Zr>#01'     

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadless