language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

branches:
  only:
  - master

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm install

script:
  - npm run watch
  - npm run test 